/*
 * DIO_cnfg.c
 *
 * Created: 9/13/2019 10:49:52 AM
 *  Author: Moawad
 */ 
#include "DIO_cnfg.h"

DIO_cnfg_t DIO_cnfg_arr [NUM_OF_PINS] =
{
	{PORT_D,PIN2,OUTPUT,LOW,NA,INITIALIZED},
	{PORT_D,PIN3,OUTPUT,LOW,NA,INITIALIZED},
	{PORT_D,PIN4,OUTPUT,HIGH,NA,INITIALIZED},
	{PORT_D,PIN5,OUTPUT,HIGH,NA,INITIALIZED},
	{PORT_D,PIN6,OUTPUT,LOW,NA,INITIALIZED},
	{PORT_D,PIN7,OUTPUT,LOW,NA,INITIALIZED},
	{PORT_B,PIN4,OUTPUT,LOW,NA,INITIALIZED}	
						
};